# tests/integration/test_end_to_end.py
"""
End-to-end integration tests.

These tests spin up a real TLS receiver in a background thread,
then fire a real TLS sender at it. Uses self-signed test certs
from tests/certs/ (generated by tests/certs/gen_test_certs.sh).

Run with:
    MESSENGER_CERT_DIR=tests/certs pytest tests/integration/ -v
"""
import os
import threading
import time
import socket
import pytest

# Point to test certs before importing messenger modules
os.environ.setdefault("MESSENGER_CERT_DIR", "tests/certs")

from messenger.receiver.server import run_receiver
from messenger.sender.connection import send_message
from messenger.common.exceptions import (
    MessageTooLargeError,
    ConnectionRefusedError,
)

BASE_PORT = 19443


def _free_port(base: int = BASE_PORT) -> int:
    """Find a free port starting from base."""
    for port in range(base, base + 100):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                continue
    raise RuntimeError("No free port found in range.")


def start_receiver(port: int, **kwargs) -> threading.Thread:
    """Start receiver in a daemon thread. Returns after binding is ready."""
    t = threading.Thread(
        target=run_receiver,
        kwargs={"port": port, **kwargs},
        daemon=True,
    )
    t.start()
    time.sleep(0.4)  # Allow time to bind
    return t


class TestBasicSendReceive:
    def test_plain_tls_message(self):
        port = _free_port()
        start_receiver(port)
        # Should not raise
        send_message("127.0.0.1", port, "Hello from integration test")

    def test_unicode_message(self):
        port = _free_port()
        start_receiver(port)
        send_message("127.0.0.1", port, "नमस्ते 🔐 Héllo")

    def test_multiple_sequential_messages(self):
        port = _free_port()
        start_receiver(port)
        for i in range(5):
            send_message("127.0.0.1", port, f"Message {i}")

    def test_max_size_message(self):
        port = _free_port()
        start_receiver(port)
        # Just under the limit — should succeed
        # JSON overhead is ~10 bytes: {"msg": "..."}
        msg = "A" * 4080
        send_message("127.0.0.1", port, msg)


class TestErrorCases:
    def test_oversized_message_blocked_at_sender(self):
        port = _free_port()
        start_receiver(port)
        with pytest.raises(MessageTooLargeError):
            send_message("127.0.0.1", port, "X" * 5000)

    def test_no_server_running(self):
        # Pick a port with no listener
        port = _free_port(29000)
        with pytest.raises(ConnectionRefusedError):
            send_message("127.0.0.1", port, "Should fail")

    def test_wrong_port(self):
        port = _free_port()
        start_receiver(port)
        wrong_port = port + 1
        with pytest.raises(ConnectionRefusedError):
            send_message("127.0.0.1", wrong_port, "Wrong port")


class TestE2EEncryption:
    def test_e2e_roundtrip(self, tmp_path):
        from messenger.crypto.e2e import generate_psk
        key_path = str(tmp_path / "e2e.key")
        generate_psk(key_path)

        # Temporarily point E2E key to our test key
        original = os.environ.get("MESSENGER_CERT_DIR")
        os.environ["MESSENGER_CERT_DIR"] = str(tmp_path)

        # Copy certs into tmp_path so receiver can find them
        import shutil
        cert_src = os.environ.get("MESSENGER_CERT_DIR", "tests/certs")
        # Restore cert dir and copy test certs to tmp_path
        os.environ["MESSENGER_CERT_DIR"] = str(tmp_path)
        for fname in ["ca.crt", "server.crt", "server.key"]:
            src = os.path.join("tests/certs", fname)
            if os.path.exists(src):
                shutil.copy(src, str(tmp_path / fname))

        try:
            port = _free_port(29100)
            start_receiver(port, e2e=True)
            send_message("127.0.0.1", port, "E2E secret message", e2e=True)
        finally:
            if original:
                os.environ["MESSENGER_CERT_DIR"] = original
